kind: pipeline
type: docker
name: CICD

trigger:
  event:
    - push

steps:
  - name: build
    image: gradle
    commands:
      - cd src
      - gradlew build
    when:
      branch:
      - master